apiVersion: v2
name: search-engine
description: A Helm chart for deploying the search engine components.
type: application
version: 1.0.0
appVersion: "1.0.0"

# A list of dependencies
dependencies:
  - name: ingress-nginx
    version: "4.0.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled

maintainers:
  - name: MaintainerName
    email: maintainer@website.com

sources:
  - https://website.com/search-engine
  - https://github.com/repository/search-engine

keywords:
  - search
  - search-engine
  - web-crawler
  - indexing
  - ranking
  - kubernetes
  - helm

home: https://website.com/search-engine
icon: https://website.com/logo.png

# The kubeVersion field specifies the required Kubernetes version
kubeVersion: ">= 1.18.0"

# Annotations to describe the chart and its usage
annotations:
  helm.sh/hook: pre-install
  helm.sh/hook-delete-policy: hook-succeeded